spring:
  thymeleaf:
    cache: false
    mode: HTML

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.bjpoweronde.springboot.blog: debug
  file:
    name: blog-dev.log
    path: log
server:
  port: 8182
